use_frameworks!

platform :ios, '8.1'

target 'CammentAds_Example' do
  pod 'CammentAds', :path => '../'

  target 'CammentAds_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
